-- hs.hotkey.bind({ "alt" }, "space", function()
--   hs.eventtap.keyStroke({ "ctrl", "shift" }, "space")
-- end)
--
-- hs.hotkey.bind({ "command", "alt" }, "space", function()
--   hs.eventtap.keyStroke({ "ctrl", "command" }, "space")
-- end)
